services:
  api-portfolio-marcusgajozo:
    build:
      context: .
      target: development
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_PORT}:27017

  mongo-express:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL_DOCKER}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo
